# Use a Node.js base image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the project dependencies
RUN npm install
RUN npm run prisma-gen


# Copy the rest of the project files to the container
COPY . .

# Set the container to run the "dev" script by default
CMD [ "npm", "run", "dev" ]
